var gamePattern = []; // to store the random pattern generated by computer

var userClickedPattern = []; // to store the pattern entered by user

var buttonColors = ["red","blue", "green", "yellow"];

var started = "false"; // so that key press will initiate the game only for the first time and rest of the keypresses are ignored until the game is over

var level = 0;

$(document).keydown(function(){ //first keypress is detected and the game is started
  if(started === "false"){
    nextSequence();
    started = "true"; // change the state of started to true so that other keypresses are ignored
  }
})

/*first the user presses any key from keyboard and the nextSequence is called and started is toggled to true. Then a new button is shown by the computer. Then the player
presses a button and the function inside this is called ($(".btn").click(function(){.......}))*/

function nextSequence(){
  userClickedPattern = []; // before starting of the new level empty the array so that it can be filled with the latest pattern entere by the user
  level++; // increment the level
  $("h1").text("Level " + level); // chnage the text of the heading to specify the level

  var randomNumber = Math.floor(Math.random()*4); // create a andom number between 0 to 3 to choose a random color from the buttoncolors array

  var randomChooseColor = buttonColors[randomNumber];
  gamePattern.push(randomChooseColor); // append the color to the gamePattern array

  $("#" + randomChooseColor).fadeIn(100).fadeOut(100).fadeIn(100); //animating the selected button
  playSound(randomChooseColor); // playing the sound
}

$(".btn").click(function(){ // if the player enters the button it is executed
  var userChosenColor = $(this).attr("id"); // id of the player selected button is appended to the userClickedPattern
  userClickedPattern.push(userChosenColor);
  playSound(userChosenColor);
  animatePress(userChosenColor);

  if (userClickedPattern[userClickedPattern.length-1] === gamePattern[userClickedPattern.length-1]){ // is the last value same as the corresponding value in the gamePattern
    if (userClickedPattern.length === gamePattern.length){ //if yes then check whether the player has entered all the buttons from the game pattern by comparing lengths of both the arrays
      setTimeout(function(){
          nextSequence();
      },1000); // if player has entered all the buttons call next sequence again that is move to the next level otherwise do nothing as there is no else statement for this if statement
    }
  }

  else{ // if the player has entered the wong value restart the game by calling the function startOver and reinitialising the variables
    var audio = new Audio("sounds/wrong.mp3");
    audio.play();
    $("h1").text("Game Over, Press Any Key to Restart");
    $("body").addClass("game-over");
    setTimeout(function(){
      $("body").removeClass("game-over");
    },200);
    startOver();
  }
})

function playSound(name){
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

function animatePress(currentColor){
    $("#" + currentColor).addClass("pressed");
    setTimeout(function(){
      $("#" + currentColor).removeClass("pressed");
    },100);
}

function startOver(){
  level = 0;
  gamePattern = [];
  started = "false";
}
